### PR TITLE
Work towards autoclose feature

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>

In #125 @Mte90 [referred](https://github.com/Mte90/Share-Backported/issues/125#issuecomment-548374701) to this event listener:

https://github.com/Mte90/Share-Backported/blob/d5d416c80c266619741aa888a1863c7dde8dece3/background.js#L21-L38

I refactored insofar, as an updated is easier implemented. However, since I'm not on Reddit, I couldn't reach the step in the share process to finish off the issue.

### CODE REVIEW

**Comment by Mte90** [comment]
I will do some tests, so with that other then Linkedin,Facebook and Twitter there will be reddit support too.

**Comment by Mte90** [comment]
So the issue with reddit is that the cssinjection was for the old design still used on old.reddit.com to fix the modal.

To detect the share we need to detect if there was a redirect inside the modal, because the url change like in other social when you share the page.
So I think that we need to detect the url change but compared to FB/TW the url doesn't having useful to detect, it is just the final post like https://www.reddit.com/r/ItalyInformatica/comments/j6112h/mozilla_italia_developer_contest_in/. So maybe for reddit we need to compare the share url with the last one in the modal.

**Comment by Ryuno-Ki** [comment]
If the CSS injection doesn't work any more, feel free to add a commit to drop (assuming that it won't work on the other instances as well).

If you say redirects: Can we hook into the History API?

**Comment by Mte90** [comment]
If it is possible I think that is not a problem use that API.

**Comment by Ryuno-Ki** [comment]
Turns out, we can't.
But you can tap into the `<title>` via `tab.title`: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab

Is there some text we can watch out for?

**Comment by Mte90** [comment]
I am not sure about the title change but it is something that can be helpful for the other services and test it

**Comment by Ryuno-Ki** [comment]
So … can you observe the title change and tell, whether it has an effect for Reddit?
I'll refactor the code then to apply different strategies based on the share target.

**Comment by Mte90** [comment]
Let me to do some tests, I will add some console.log of the title and url to track the changes and report here.

**Comment by Mte90** [comment]
Ok if the title is changed is good to detect the submit, also the change of the url is fine too.
I think that is fine too also for other social networks so maybe we can implement for reddit and later also for others.

**Comment by Ryuno-Ki** [comment]
I didn't observe a change in URL when looking at reddit (and getting redirected to their Login page).

**Comment by Mte90** [comment]
On publishing the post the title is changed

**Comment by Ryuno-Ki** [comment]
Do you want to add a commit to this PR?
Or shall I first implement functions for different strategies?

**Comment by Mte90** [comment]
If you can do it will be awesome, with a check for service.
So I will do a later a check for the various services so maybe we can remove the check of the url and add this auto close for other services.
Usually this modal on submit will do a refresh of the page and the title changes based to that.

**Comment by Ryuno-Ki** [comment]
@Mte90 Updated.
This PR needs an update regarding the title, otherwise Reddit share will close on Log in screen.
I have implemented a first branching construct for picking a strategy.
Normally you would use Dependency Injection in a OOP fashion (which we don't use in background.js).

After the next major release, I'd like to refactor some bits of code to easier share configuration options (like share-target <-> url relationships).

**Comment by Mte90** [comment]
I am testing it but doesn't work.
How are you testing it? Also with other social?

**Comment by Ryuno-Ki** [comment]
„doesn't work”?

I am not logged into Reddit (but allow 3rd-party JavaScript for reddit.com).
I go to any non-about page and share it via Reddit.
Right now, it looks for the URL title and closes once it transitions to the Log In view in the modal.
I haven't tried other share targets.

What are your steps?

**Comment by Mte90** [comment]
I am testing the `urlChangeStrategy` maybe the best way is to create something that compare the original url with the one in that moment and close the modal.
In this way we can track all the pages and ignore the title part except if includes `Log In` or other similar terms.
In this way we can inform the user to login but we can offer a wide support for auto close.

**Comment by Ryuno-Ki** [comment]
The „Log in” was meant to be replaced with a key phrase you found via testing.
Without a Reddit account, I hadn't much options on their page.

**Comment by Mte90** [comment]
I think that we can keep that, I am just looking how to improve the urlchangestrategy to detect when the url changed from the modal opening.

**Comment by Ryuno-Ki** [comment]
Compare `sbPrevUrl` with `tabinfo.url`.

If you say, that „we can keep that”: What is needed for integration of this PR?
What can be done in a follow-up PR?

I mean, the title says „working towards” - not completing it ;-)

**Comment by Mte90** [comment]
Yep, I think that compare should be enough to approve this pr.

**Pull request merged**
