### PR TITLE
Use URLSearchParams for share URLs & SVGs for icons

### PR DESCRIPTION
**Pull request by shgysk8zer0**
- Use URLSearchParams to create URLs for window.open (should avoid any issues from special characters in URLs, etc. in URLs & text)
- Added SVG icons from WikiMedia and used instead of data: URIs
- Do not strip "|" from titles/text (URLSearchParams makes safe)
- Added Gmail share option, with SVG logo
- Set sizes and other config using `const`s
- Fixed use of "&" instead of "&amp;" in `data-share` attributes

### CODE REVIEW

**Comment by shgysk8zer0** [comment]
I checked, and using URLSearchParams avoids needing to strip out "|". Only thing I could not test is Telegram.

**Comment by Mte90** [comment]
I will add your name in the readme!

**Comment by Mte90** [comment]
I didn't know that the URL api is so amazing, also thank you for the ES6 code. I have to learn it but I so busy in many things :-)

**Comment by shgysk8zer0** [comment]
Glad to help. And, yeah, URL API is pretty useful, especially for building more complex query strings.

**Pull request merged**
