### PR TITLE
Fixed width bug

### PR DESCRIPTION
**Pull request by Sav22999**
- Fix bug #73
- Added ad error message if there isn't services visbile (if all of them are hidden)

So I updated modal.css and modal.js

### CODE REVIEW

**Comment by Mte90** [comment]
There are conflicts in this branch

**Comment by Sav22999** [comment]
... ? I don't know. What can I do to fix them?

**Comment by Mte90** [comment]
You didn't reset your branch after my merge and changes of yesterday i guess.
Also you are using the master branch that always create issue, instead of a specific one that will certainly avoided the error :-)

**Comment by Sav22999** [comment]
Yes, I'm using master branch, you're right. But I merged, yesterday, your changes (in fact you can see there is a commit "Merge remote- ....").
I'm so sorry about these confics and these problems

**Comment by Sav22999** [comment]
Are there still conflicts?

**Pull request merged**
