### PR TITLE
New modern GUI

### PR DESCRIPTION
**Pull request by Sav22999**
- Updated GUI in Options (now it looks like Firefox preferences)
- Updated panel of extension
- Fixed bug (when lines were 5, so added "lines-5" in modal.css)

consequently updated:
- modal.js
- modal.css
- opstions.html

#83

### CODE REVIEW

**Comment by Sav22999** [comment]
The apparence is this: 
immagine

immagine

Tell me your opinion

**Comment by Sav22999** [comment]
immagine

**Comment by Sav22999** [comment]
(wait a moment before merge, in case)

**Comment by Sav22999** [comment]
I've updated HR (actually I removed it and I set border-top, padding-top and margin-top in "Save" section). This is the new appearance of it
immagine

**Comment by Mte90** [comment]
Cool, now the big issue is the yahoo logo that is very horrible...

**Comment by Mte90** [comment]
yes is very horrible with the new ui is very horrible too

**Comment by Sav22999** [comment]
You're right. Tell me some minutes ... I get a better icon, maybe :)

**Comment by Sav22999** [comment]
immagine

That's bettere, I think ... 😄

**Pull request merged**
