### PR TITLE
Open share modal via Ctrl+Alt+Y. Refs #114

### PR DESCRIPTION
**Pull request by Ryuno-Ki**
Signed-off-by: André Jaenisch <andre.jaenisch@posteo.de>

### CODE REVIEW

**Review by Mte90 — CHANGES_REQUESTED** [review]
We need a mention in the readme of that hotkey so I can merge it :-)

**Comment by Ryuno-Ki** [comment]
That's why I said, „Refs” not „Closes” :-)

Do you want to have it only in the README?
I'd imagine, the description on AMO needs a hint, too.
Perhaps also as a hint on the footer of the share icons in the modal? Or in the preferences?

**Comment by Mte90** [comment]
I think in the readme and I will updated the addons stores, in the modal I think that will be too long to scroll.

**Comment by Ryuno-Ki** [comment]
Resolved merge conflict, solved a logic bug (what if the first share target is disabled?) and added a section to the readme.

Take it away, @Mte90!

**Pull request merged**
